// COMMON ACTION
export const ERROR = 'ERROR';

// USER
export const SET_USER = 'SET_USER';

// SONGS
export const TOGGLE_PLAY = 'TOGGLE_PLAY';
export const GET_HOME_PLAYLISTS = 'GET_HOME_PLAYLISTS';
export const GET_SONG = 'GET_SONG';
export const GET_PLAYLIST_INFO = 'GET_PLAYLIST_INFO';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORY_PLAYLISTS = 'GET_CATEGORY_PLAYLISTS';
